//
// Created by haosheng lin on 2018/5/5.
//
#include <jni.h>

#ifndef VIDEOAUDIOPROJECT_DECODE_H
#define VIDEOAUDIOPROJECT_DECODE_H


/* DO NOT EDIT THIS FILE - it is machine generated */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jonesx_videoplayer_VideoPlayer
 * Method:    play
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_linhao_FfmpegDecodeVideoActivity_decode
        (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jstring JNICALL
Java_com_linhao_FfmpegDecodeVideoActivity_avcodecinfo(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

#endif //VIDEOAUDIOPROJECT_DECODE_H
